version: '3.6'

services:
  build_react:
    image: react
    build:
      context: .
      dockerfile: Dockerfile-react
    command: cp -a /opt/tigerpath/ /target
    volumes:
      - tigerpath-volume:/target
  react:
    image: react
    command: bun run start
    ports:
      - 3000:3000
    volumes:
      - tigerpath-volume:/target
    depends_on:
      - build_react
  build_web:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    command: cp -a /opt/tigerpath/ /target
    volumes:
      - tigerpath-volume:/target
  web:
    image: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - tigerpath-volume:/target
    depends_on:
      - build_web

volumes:
  tigerpath-volume: {}
